version: '3.7'
services: 
    app:
        restart: unless-stopped
        build: .
        ports:
            - "3000:3000"
        depends_on: 
            - mongodb
        environment: 
            - DEBUG=app:*
            - MONGODB_URI=mongodb://root:toor@mongodb/myterm?authSource=admin
        volumes: 
            - ./ssl:/app/ssl
    mongodb:
        restart: unless-stopped
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=toor
        ports: 
            - 27017:27017