version: '3.7'
services: 
    app:
        restart: unless-stopped
        build: .
        ports:
            - "3000:3000"
        depends_on: 
            - mongodb
        environment: 
            - DEBUG=app:*
    mongodb:
        image: mongo
        ports: 
            - 27017:27017